uri: "/goods/info/package" #点餐-获取套餐
retData:
  - glid: 5

"result": {
  "data": {
    "info": {
      "id": 98,
      "sid": 96,
      "glid": 246,
      "name": "美味不用等",
      "photo": [
        "https://img.weizhilian.com/10006/96/image/puduct/edmjip3rbsuhho02bd2u9ubm1m"
      ],
      "broadcast": 5000,
      "showEn": 2,
      "showEnName": "",
      "limitation": 0,
      "detailShow": 2,
      "detailName": "商品详情",
      "detailContent": [
      {
        "text": [
          ""
        ],
        "title": ""
      }
      ],
      "atime": 1555398955,
      "photoUrl": [
        "https://img.weizhilian.com/10006/96/image/puduct/edmjip3rbsuhho02bd2u9ubm1m"
      ],
      "gid": 373,
      "cid": 4,
      "glname": "美味不用等"
    },
    "package": {
      "id": 22,
      "sid": 96,
      "glid": 246,
      "discountTips": 2,
      "discountTop": 1,
      "discount": [
      {
        "amount": "100",
        "discount": "0"
      }
      ],
      "list": [
      {
        "id": 33,
        "sid": 96,
        "glid": 246,
        "name": "主材",
        "sort": 1,
        "option": 1,
        "limit": 0,
        "multi": 1,
        "parts": [
        {
          "id": 116,
          "gpid": 33,
          "sid": 96,
          "gid": 11,
          "name": "车厘子ll",
          "price": 1000,
          "vipPrice": 800,
          "sort": 3,
          "backup": 2,
          "default": 1,
          "packagePrice": 1000,
          "packageVipPrice": 800,
          "packageName": "车厘子ll",
          "photo": [
            "https://img.weizhilian.com/10006/96/image/puduct/1le4bpa3kbmknvshijkfv3ikfh"
          ],
          "stock": 99968,
          "boxNum": 1,
          "boxPrice": 0,
          "dineIn": 1,
          "takeAway": 1,
          "takeOut": 1,
          "pickUp": 2,
          "min": 1,
          "unit": "份",
          "type": 1,
          "shelves": 1,
          "spec": "",
          "saleTime": 1,
          "saleTimeLimit": [],
          "isSale": 1
        }
        ]
      }
      ]
    },
#    "property": []
  },
  "status": 200,
  "code": 0,
  "message": "",
  "serverTime": 1556357203.9490499
}


