# 请求头部
header:
  content-type: "application/json"
  bid: "10006"
  sid: "96"
  uid: "63"
  token: "2414c603b629c76ac770183c8bb21cc7" #token指定用户并直接修改过期时间
  locale: "1"
  miniversion: "1"
  sdkversion: "1"

#请求环境域名
#host: "http://127.0.0.5"
host: "https://api-testing.weizhilian.com"
case_url: "http://192.168.31.243"
#case_url: "http://192.168.103.126"
#case_url: "http://148.70.137.31:8171"

# 接收测试结果的邮件，多个用，隔开
user_email: "1357282015@qq.com,1358448980@qq.com"

uri:
  # 用户信息授权（登录、注册）暂时无法模拟授权登录不执行
  loginUrl: "/user/init/index"
  # 店铺会员初始化/shop/shop/list
  initUserShop: "/user/init/shop"
  #获取点餐菜品列表
  getGoodsListUrl: "/goods/list/index"
  #获取菜品规格详情
  getGoodsDetailUrl: "/goods/info/spec"
  #获取菜品分类列表
  getCateListUrl: "/goods/category/list"
  #获取加购数据
  getAddSlpListUrl: "/goods/list/addition"
  #用户下单
  postOrderUrl: "/order/add"
  # 我的-会员等级获取
  getVipLevel: "/user/vip/data"
  # 我的-用户个人数据获取
  getUserInfo: "/user/info/info"
  # 我的地址-获取用户收货地址列表
  getUserAddress: "/user/address/list"
  # 我的地址-新增用户收地址
  addUserAddress: "/user/address/add"
  # 我的地址-修改用户收货地址
  editAddress: "/user/address/update"
  # 我的地址-删除用户地址
  delAddress: "/user/address/delete"
  # 我的订单-获取用户订单列表
  getOrderList: "/order/list"
  # 我的订单-获取计数统计
  getOrderCount: "/order/count"
  # 我的订单-取消订单
  closeOrder: "/order/cancel"
  # 店铺-城市列表
  cityList: "/shop/shop/city-list"
  # 店铺列表
  shopList: "/shop/shop/list"
  # 店铺-员工列表
  workerList: "/worker/worker/list"
  # 店铺-品牌故事
  storyDetail: "/shop/shop/story-detail"
  # 店铺-员工点赞点踩
  workerEvaluation: "/worker/worker/evaluation"
  # 店铺-评论列表
  commentList: "/comment/comment/index"
  # 店铺-发布评论
  addReplay: "/comment/comment/add-replay"
  # 店铺详情
  shopDetail: "/shop/shop/detail"
  # 店铺-菜品推荐列表
  recommendList: "/goods/recommend/list"
  # 评论点赞
  changeLike: "/comment/comment/add-like"
  # 订单评价
  addOrderComment: "/comment/comment/add-comment"
  # 我的消息-获取消息通知列表
  getMessageList: "/msg/push/list"
  # 我的消息-获取通知数量
  getMessageCount: "/msg/push/detail"
  # 我的消息-删除消息
  delMessage: "/msg/push/delete"
  #获取IM用户信息
  getIMUserInfo: "/msg/im/getUserInfo"
  # 充值-获取充值列表
  getRechargeList: "/activity/recharge/list"
  # 充值-充值统计数据
  getRechargeCount: "/user/data/recharge-amount"
  # 获取用户邀请奖励用户列表-按人数
  getUserInvitations: "/user/data/invitations-by"
  # 充值-获取用户充值明细
  getRechargeDetail: "/user/data/recharge"
  # 打赏金额配置
  getRewardSet: "/shop/shop/reward-set"
  # 打赏生成第三方订单
  rewardPay: "/worker/worker/reward-pay"
  # 评论奖励-列表
  commentsRewardList: "/user/info/comment"
  # 评论奖励-消费明细
  getSpendingInfo: "/user/info/spending"
  # 评论奖励-获取评总金额
  getCommentAmount: "/user/data/comment-amount"
  #评论奖励-获取评论统计
  getCommentUserCount: "/comment/comment/get-user-count"
  # 我的钱包-邀请奖励金额统计
  getInvitationsAmount: "/user/data/invitations-amount"
  # 我的钱包-获取赠送、返还金额列表
  getUserGiveList: "/user/data/give"
  # 充值-获取充值明细
  getRechargeDetailList: "/user/data/recharge"
  # 点餐-检测菜品是否正常
  checkGoodsStatusList: "/goods/goods/check"
  # 下单-获取商家预约配送时间
  getStoreDistributionList: "/shop/shop/get-send-time"
  # 店铺-获取桌位详情
  getStoreTableDetail: "/shop/table/detail"
  # 店铺-获取wifi列表
  getWifiSetting: "/shop/wifi/wifi-list"
  # 获取可用优惠券列表
  getAvailableCoupon: "/activity/coupon/coupon-able-list"
  # 获取分享优惠券
  getShareCoupon: "/activity/coupon/get-share"
  # 获取邀请优惠券信息
  getInvitationsInfo: "/activity/coupon/get-invitations"
  # 获取菜品券可发列表
  getCouponGoodsList: "/activity/coupon/coupon-goods-able-list"
  # 获取我的优惠券列表
  getMyCouponList: "/activity/coupon/list"
  # 获取邀请奖励规则数据
  getInvitationsRule: "/activity/coupon/invitations-rule"
  # 获取邀请奖励明细
  getInvitationsDetail: "/user/data/invitations"
  # 邀请奖励消费人数统计
  handelInvitationsUser: "/user/data/invitations-by-count"
  # 优惠券使用总计优惠金额
  getCouponUsedAmount: "/activity/coupon/used-amount"
  # 领券中心列表
  getCouponCenterList: "/activity/coupon/center"
  # 获取星座列表
  getStarSignList: "/user/info/star-sign"
  # 获取单条评论详情
  getCommentDetail: "/comment/comment/get-detail"
  #  单条评论删除
  delComment: "/comment/comment/delete"
  # 菜品相关配置
  foodsConfigInfo: "/goods/goods/config"
  # 修改桌位状态
  setTableStatus: "/shop/table/set-status"
  # 获取用户邀请奖励比例
  getInviteRebate: "/activity/coupon/get-invite-rebate"
  # 获取广告位数据
  getAdListData: "/goods/advertising/list"
  # 获取有事找我历史消息
  getOldIMMsg: "/msg/im/imList"
  # 获取注册弹窗信息配置
  getRegConfigInfo: "/activity/config/get-reg"
  # 保存用户自提的手机号
  saveUserSelfMobile: "/user/info/save-picked-up-info"
  # 获取用户自提的手机号
  getUserSelfMobile: "/user/info/picked-up-info"
  # 店铺是否开启邀请返现
  isCashBack: "/activity/coupon/check-invite-conf"
  # 我的钱包-余额统计
  getAccountBalance: "/user/data/balance"
  # 充值-添加充值订单
  postRecharge: "/user/vip/recharge"
  # 注册会员-获取验证码
  getUserCode: "/user/vip/code"
  # 下单-计算配送费用
  getDistancePic: "/shop/shop/get-distribution-price"
  # 我的-获取未读消息数
  getUnMsgDataNumber: "/msg/push/count"
  # 评论标签
  getOrderCommentTags: "/comment/comment/get-label-list"
  # 优惠券转赠
  coupongiving: "/activity/coupon/donate"
  # 检查当前用户是否已领取分享券
  checkReceiveShare: "/activity/coupon/check-receive-share"
  # 获取已领取的分享优惠券列表
  getReceiveShare: "/activity/coupon/receive-share"
  # 领取分享优惠券
  getLuckyShare: "/activity/coupon/lucky-share"
  # 我的订单-订单详情
  orderDetail: "/order/detail"
  #获取套餐详情
  getPackageDetailUrl: "/goods/info/package"
  #店铺-菜品推荐详情
  recommendDetail: "/goods/recommend/one"
  #桌位列表
  tableList: "/shop/table/list"


  #从这里开始没成功++++++++++
  # 注册会员-一键注册
  autoPostUserReg: "/user/vip/auto-reg"
  # 注册会员-领取红包
  receiveDiscount: "/user/vip/reg"
  # 店铺-上传wifi连接日志
  postWifiConnLog: "/shop/wifi/save-log"
  # 提交错误日志
  postLogUrl: "/report"
  # 一键获取手机号激活
  postUserMobileData: "/user/vip/wx-mobile-reg"




  # 菜品券分享
  couponGoodsSent: "/activity/coupon/coupon-goods-sent"
  # 菜品券领取
  couponGoodsReceive: "/activity/coupon/receive"
  # 菜品券撤销
  couponCancelDonate: "/activity/coupon/cancel-donate"

  # 邀请奖励返还
  handleBackInvitations: "/user/data/re-give"


  # 获取单张菜品券信息
  handleFoodCouponDetail: "/activity/coupon/detail"
  # 修改个人信息(领取生日券)
  getBirthCoupon: "/user/info/update"
  # 检查购物车单品金额及库存问题
  checkSlpGoodsData: "/goods/goods/for-order-info"
  # 分享券上报
  shareCallback: "/activity/coupon/share-callback"

  # 下单时店铺切换列表
  storeByType: "/shop/shop/get-shop-by-type"
  #获取全屏点餐列表
  getFullScreenGoodsUrl: "/goods/full-screen/list"

  #获取菜品可售时间
  getGoodsSaleTimeUrl: "/goods/list/sale-time"
  # 我的订单-删除订单
  delOrder: "/order/delete"

  # 我的订单-立即支付
  postOrderPay: "/order/pay"

